version: '3.9'
services:
  apache:
    image: php:7.4-apache
    container_name: asir_servidor_apache
    ports:
      - '8008:80'
    volumes:
      - ./Servidor/Pagina1:/var/www/html
      - ./Servidor/ConfApache:/usr/local/apache/htdocs


      